robotframework/robotframework

atest/robot/tidy/tidy.robot
atest/testdata/tidy/else_tidy.robot
atest/testdata/tidy/else_untidy.robot
src/robot/writer/rowsplitter.py

This is for #1273. This approach is only good for ELSE/ELSE IF - it's not the generic approach of preserving ellipsis.

Tidy ELSE and ELSE IF onto separate lines

---

doc/userguide/src/CreatingTestData/CreatingUserKeywords.rst
doc/userguide/src/ExecutingTestCases/OutputFiles.rst

One duplicate word and one miss spelled.

Fixed couple typos.

---

src/robot/libraries/BuiltIn.py

Trying to take the best of https://github.com/robotframework/robotframework/pull/1947 and https://github.com/robotframework/robotframework/pull/1946

Enhance doc to be more explicit on Run Keyword If return value. See #1945

---

src/robot/libraries/Telnet.py

To prevent endless negotiation loops with the telnet options, we must not
reply to already negotiated options.

Telnet: Keep track of telnet negotiation options

---

src/robot/output/output.py
utest/api/test_run_and_rebot.py
utest/resources/Listener.py
utest/resources/runningtestcase.py
utest/running/test_running.py

Fix for https://github.com/robotframework/robotframework/issues/1992

Unregister listeners on Output.close

---

src/robot/conf/settings.py
src/robot/output/listeners.py
src/robot/run.py
src/robot/running/model.py
src/robot/utils/__init__.py
src/robot/utils/text.py
utest/api/test_run_and_rebot.py
utest/conf/test_settings.py
utest/output/test_listeners.py
utest/running/test_running.py
utest/utils/test_text.py

implements https://github.com/robotframework/robotframework/issues/1969

Allow to pass listener instances to robot.run

---

atest/robot/libdoc/console_viewer.robot
atest/robot/libdoc/python_library.robot
src/robot/libraries/Telnet.py

Aims to implement issue #2079. This still missing specific tests, but I should be able to create them soon. I've just fixed current tests to work with the new argument. Tests passed on my local machine.

Telnet Library: allow control over connection timeout

---

atest/robot/standard_libraries/builtin/set_test_message.robot
atest/testdata/standard_libraries/builtin/set_test_message.robot
src/robot/libraries/BuiltIn.py

This is a resurrection of https://github.com/robotframework/robotframework/pull/2189 which was killed by GitHub's reaction to an attempt to amend the commit based on the comments made in the original pull request.

Fixed TEST_MESSAGE not reacting to SetTestMessage

---

doc/userguide/src/ExtendingRobotFramework/CreatingTestLibraries.rst

Fix python code in the document.

fix-python-code-in-doc

---

src/robot/libraries/Collections.py

Fix error in documentation of List Should Not Contain Value keyword

---

AUTHORS.txt
atest/robot/standard_libraries/builtin/verify.robot
atest/testdata/standard_libraries/builtin/verify.robot
src/robot/libraries/BuiltIn.py

Added Acceptance Tests to cover the new functionality for both keywords;

Implementation of the Case Insensitive flag for the  "Should (Not) End With" keyword pair

---

.gitignore
doc/api/code_examples/disable.py
doc/api/code_examples/filtertc.py
doc/userguide/src/ExecutingTestCases/ConfiguringExecution.rst

Add some useful examples of prerun modifiers to the docs #2299

prerun modifier documentation

---

.gitignore
atest/robot/standard_libraries/builtin/set_test_message.robot
atest/testdata/standard_libraries/builtin/set_test_message.robot
src/robot/libraries/BuiltIn.py

fix for Set Test Message with the combined INFO and HTML

---

atest/robot/output/xunit.robot
atest/testdata/misc/non_ascii.robot
src/robot/reporting/xunitwriter.py

xUnit: represent times as floats not ints

---

doc/userguide/ug2html.py

Tested only in Linux with ~~both python 2.7.15 and~~ 3.6.5.
It was modified to run only with python 3.

Adapted u2html.py to run under Python 3.

---

atest/robot/output/xunit.robot
src/robot/reporting/xunitwriter.py

please close the previous commit #2984
and review this commit according to #2979 
Thanks for your help!

add time attribute into the testsuite element of the Xunit out put file

---

atest/robot/standard_libraries/collections/dictionary.robot
atest/robot/standard_libraries/collections/list.robot
atest/testdata/standard_libraries/collections/dictionary.robot
atest/testdata/standard_libraries/collections/list.robot
src/robot/libraries/Collections.py

Support for deep copies in Copy List and Copy Dictionary keywords

---

BUILD.rst

Sonatype http to https

---

doc/userguide/src/GettingStarted/Demonstration.rst

Fixed Web demo and demo projects links

---

doc/userguide/src/ExecutingTestCases/ConfiguringExecution.rst

fixes typo in userguide
found and fixed by :robot: ai
:laughing:

fixes typo in userguide

---

BUILD.rst
CONTRIBUTING.rst
atest/README.rst
doc/releasenotes/rf-2.9.1.rst
doc/releasenotes/rf-3.0.1.rst
doc/releasenotes/rf-3.0.rst
doc/releasenotes/rf-3.0a1.rst
doc/releasenotes/rf-3.0a2.rst
doc/releasenotes/rf-3.0b1.rst
doc/releasenotes/rf-3.1.rst
doc/releasenotes/rf-3.1a2.rst
doc/releasenotes/rf-3.1b1.rst
doc/releasenotes/rf-3.1rc1.rst
doc/releasenotes/rf-3.1rc2.rst
doc/userguide/src/ExecutingTestCases/BasicUsage.rst
doc/userguide/src/SupportingTools/Libdoc.rst
utest/README.rst

Some minor doc edits while I am reading...

Docs minor fixes

---

src/robot/libraries/Collections.py

Signed-off-by: Stavros Ntentos <133706+stdedos@users.noreply.github.com>

Fix typo on Collections#combine_lists

---

src/robot/libraries/Screenshot.py

Add note about ScreenCapLibrary

---

atest/robot/test_libraries/disable_public_methods.robot
atest/testdata/test_libraries/DisablePublicMethods.py
atest/testdata/test_libraries/disable_public_methods.robot
doc/userguide/src/ExtendingRobotFramework/CreatingTestLibraries.rst
src/robot/running/testlibraries.py

This is the PR for the first part of #3019 as discussed on Slack https://robotframework.slack.com/archives/C0K0240NL/p1560209961022000. The second PR related to this issue is in progress.

Disable public methods

---

.gitignore

* Remove duplicate pattern
* Ignore virtualenv creation locally
Signed-off-by: Stavros Ntentos <133706+stdedos@users.noreply.github.com>

Small changes to .gitignore

---

atest/robot/standard_libraries/process/stdout_and_stderr.robot
atest/testdata/standard_libraries/process/stdout_and_stderr.robot
src/robot/libraries/Process.py

Process: Add DEVNULL option to disable stdout and stderr

---

.github/workflows/acceptance_tests.yml
.github/workflows/tests.yml
.github/workflows/unit_tests.yml

In continuation of #3386:
- unit tests run on push and pull request events
- acceptance tests runs on pull request and [each 12 hours](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onschedule)
- run tests on Jython '2.7.2b2', '2.7.0', '2.7.1'

Unit & Acceptances tests run - option 2

---

.github/workflows/acceptance_tests_cpython.yml
.github/workflows/acceptance_tests_ironpython.yml
.github/workflows/acceptance_tests_jython.yml
.github/workflows/unit_tests.yml

https://github.com/actions/checkout/releases

Upgrade GitHub actions/checkout@v1 --> v2

---

.github/workflows/acceptance_tests_cpython.yml
.github/workflows/acceptance_tests_jython.yml
.github/workflows/unit_tests.yml

- Screenshot library tests on Python/PyPy/Jython
- Unit tests on MacOS using Jython

Run screenshot tests on Linux (Python / Jython)

---

atest/testdata/running/dynamic_teardown.robot

Removed tab using from robot code.

Removed tabs in code from robot-file

---

src/robot/utils/misc.py
utest/utils/test_misc.py

improve plural_or_not

---

src/robot/libdocpkg/specbuilder.py

Fix simple typo: compatiblity -> compatibility

---

src/robot/libraries/Screenshot.py

Fixes segmentation fault when using Screenshot with wxPython on Linux and Python 2.7

---

.github/workflows/unit_tests.yml

@Hi-Fi. @pekkaklarck, have a look, please.

Run unit tests on IronPython 2.7.9 (Windows)

---

src/robot/libraries/dialogs_py.py

Bring to front wasn't working in Windows server 2016
this commit fixes issue #3492

Update dialogs_py.py bring to front

---

atest/robot/rebot/merge.robot
atest/robot/rebot/merge_html.robot
atest/robot/rpa/rebot_rpa_tasks.robot
src/robot/result/merger.py
utest/result/test_resultbuilder.py

Make rebot's merge message less confusing

---

.github/workflows/acceptance_tests_cpython.yml
.github/workflows/unit_tests.yml

- Run acceptance tests if changes in any file in `src`, `atest` directories and its subdirectories, excluding any changes in `*.rst` files.
- Run unit tests if changes in any file in `src`, `utest` directories and its subdirectories, excluding any changes in `*.rst` files.
- Run any workflow if its configuration changes. Based on https://github.community/t5/GitHub-Actions/Trigger-a-workflow-on-change-to-the-yml-file-itself/td-p/49255.
Based on https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths

Run workflows in case of changes in specific directories

---

.github/workflows/acceptance_tests_cpython.yml
.github/workflows/unit_tests.yml

Refer to [Slack discussion](https://robotframework.slack.com/archives/CSZJ5LUER/p1585825297021700).

Disable NTP on macOS runner

---

.github/workflows/acceptance_tests_cpython.yml
.github/workflows/acceptance_tests_jython.yml
.github/workflows/unit_tests.yml

Upgrade setup-python and upload-artifact actions version to recent ones

---

src/robot/libraries/BuiltIn.py

in the python docs.
Pull request for issue #3596

Replaced the old :FOR loop syntax for the new FOR and END syntax

---

atest/robot/keywords/type_conversion/annotations.robot
atest/robot/keywords/type_conversion/default_values.robot
atest/robot/keywords/type_conversion/keyword_decorator.robot
atest/testdata/keywords/type_conversion/Annotations.py
atest/testdata/keywords/type_conversion/annotations.robot
atest/testdata/keywords/type_conversion/annotations_with_aliases.robot
atest/testdata/keywords/type_conversion/default_values.robot
atest/testdata/keywords/type_conversion/keyword_decorator.robot
atest/testdata/keywords/type_conversion/keyword_decorator_with_aliases.robot
doc/userguide/src/ExtendingRobotFramework/CreatingTestLibraries.rst
src/robot/running/arguments/typeconverters.py

Prevent None conversion by default.
Fixes enum conversion.

None is not by default converted

---

atest/robot/libdoc/default_escaping.robot
atest/robot/parsing/escaping.robot
atest/testdata/libdoc/default_escaping.py
atest/testdata/libdoc/default_escaping.resource
atest/testdata/parsing/escaping.robot
doc/userguide/src/CreatingTestData/TestDataSyntax.rst
src/robot/utils/escaping.py
utest/utils/test_escaping.py

Removed ignoring Space after line break

---

doc/schema/robot-xsd10.xsd
doc/schema/robot-xsd11.xsd

added SKIP status and removed critical attribute (fixes #3726)

---

atest/resources/atest_resource.robot
atest/robot/libdoc/LibDocLib.py
atest/robot/libdoc/html_output.robot
atest/robot/libdoc/json_output.robot
atest/robot/libdoc/libdoc_resource.robot
atest/robot/libdoc/type_annotations.robot
atest/testdata/keywords/type_conversion/Annotations.py
atest/testdata/keywords/type_conversion/annotations.robot
atest/testdata/libdoc/DynamicLibrary.json
doc/schema/libdoc.03.xsd
doc/schema/libdoc_schema.json
src/robot/htmldata/libdoc/libdoc.css
src/robot/htmldata/libdoc/libdoc.html
src/robot/libdocpkg/jsonbuilder.py
src/robot/libdocpkg/model.py
src/robot/libdocpkg/specbuilder.py
src/robot/libdocpkg/xmlwriter.py
src/robot/running/arguments/argumentspec.py
src/robot/running/arguments/py3argumentparser.py
utest/running/test_argumentspec.py

Great work from @Snooz82 !!!!! 🏆

Added Union support to libdoc (#3748)

---

.github/dependabot.yml
.github/workflows/acceptance_tests_cpython.yml
.github/workflows/acceptance_tests_cpython_pr.yml
.github/workflows/acceptance_tests_jython.yml

Dependabot to check action updates

Fixed environment variables

---

src/robot/model/fixture.py
src/robot/model/keyword.py
src/robot/model/testcase.py
src/robot/model/testsuite.py
utest/model/test_fixture.py
utest/model/test_testcase.py

This allows resetting them with `setup = None`

model: setters for testcase setup and teardown

---

doc/releasenotes/rf-3.2.rst
doc/releasenotes/rf-3.2a1.rst
doc/releasenotes/rf-3.2b1.rst
doc/releasenotes/rf-3.2b2.rst
doc/releasenotes/rf-3.2rc1.rst
doc/releasenotes/rf-3.2rc2.rst
doc/userguide/src/CreatingTestData/Variables.rst
src/robot/libraries/DateTime.py

Also "to some extend" -> "to some extent" near one of the other fixes.

Fix typo `datatime` -> `datetime`

---

src/robot/parsing/model/statements.py
utest/parsing/test_statements.py

Revert adding __eq__ methods to Statement class

---

src/robot/parsing/model/statements.py
utest/parsing/test_model.py

this corrects issue: #3857
also added some simple unit tests

PR for #3857: correct Error statement to correctly handle FATAL_ERRORS

---

atest/robot/cli/rebot/remove_keywords/all_passed_tag_and_name.robot
src/robot/result/xmlelementhandlers.py

@pekkaklarck @mkorpela Hi, guys! I try to fix this problem.
**Tests before fix:**
**After fix:**

#ISSUE-4009 try to fix problem with doc tag

---

atest/robot/standard_libraries/string/generate_random_string.robot
atest/testdata/standard_libraries/string/generate_random_string.robot
src/robot/libraries/String.py

Implementation for #4133.
Allows the use of `Generate Random String` with a range of values, instead of a single value.

Support generating random strings with random length

---

atest/robot/output/xunit.robot
atest/robot/rebot/xunit.robot
src/robot/reporting/xunitwriter.py

This PR is for solving issue #3944 Request for log_property functionality for xunit writer.
Based on previous draft PR #4165

Properties and property elements to xunit output

---

src/robot/output/console/dotted.py

fix incorrect spelling of "SKIPPED"

---

doc/userguide/src/CreatingTestData/ResourceAndVariableFiles.rst

Documentation for "Support importing variable files as modules. #4226

Documentation for "Support importing variable files as modules. #4226

---

atest/robot/cli/console/expected_output/dotted_exitonfailure.txt
atest/robot/cli/console/expected_output/dotted_with_skip.txt
atest/robot/cli/console/expected_output/warnings_and_errors_stdout_dotted_10.txt
atest/robot/output/processing_output.robot
atest/robot/output/statistics.robot
atest/robot/output/statistics_in_log_and_report.robot
atest/robot/output/statistics_with_rebot.robot
atest/robot/output/suite_and_test_id_in_output.robot
atest/robot/output/xunit.robot
atest/robot/rebot/merge.robot
atest/robot/rebot/xunit.robot
atest/testdata/misc/suites/01__suite_with_prefix/01__tests_with_prefix.robot
atest/testdata/misc/suites/suite_with_double_underscore__/tests_with_double_underscore__.robot
src/robot/parsing/suitestructure.py
src/robot/running/builder/parsers.py
utest/running/test_builder.py
utest/testdoc/test_jsonconverter.py

this are the fixes for #4249
do you have an idea, where I should put the testcases for it?

correct handling of double underscore at end of suite names fixes #4249

---

atest/robot/cli/console/max_assign_length.robot
atest/testdata/misc/long_variable_value.robot
doc/userguide/src/Appendices/CommandLineOptions.rst
src/robot/conf/settings.py
src/robot/run.py
src/robot/utils/text.py
utest/testdoc/test_jsonconverter.py

Here I try to implement #3410
@pekkaklarck Hi! I couldn't reopen last PR(https://github.com/robotframework/robotframework/pull/4051) so I have created new.

ISSUE-3410 Added `--maxassignlength` option

---

doc/userguide/src/ExecutingTestCases/OutputFiles.rst

Typo correction to OutputFiles.rst

---

src/robot/htmldata/libdoc/libdoc.css
src/robot/htmldata/libdoc/libdoc.html

Signed-off-by: René <snooz@posteo.de>

fixed-type-links

---

src/robot/htmldata/libdoc/libdoc.css
src/robot/htmldata/libdoc/libdoc.html

https://guttural-year.surge.sh/Browser.html

small margin and no list style

---

.gitignore
src/robot/parsing/lexer/blocklexers.py
src/robot/parsing/lexer/statementlexers.py
src/robot/parsing/lexer/tokenizer.py

I've spent a couple of hours optimizing some low-hanging fruits in the parsing (while for RF this may not be a huge gain, the language servers which use the parsers can gain quite a bit since parsing is a bottleneck on big documents).

Make parsing 17% faster.

---

src/robot/reporting/xunitwriter.py

Maintenance: XUnitFileWriter code streamlined

---

atest/robot/standard_libraries/collections/dictionary.robot
atest/testdata/standard_libraries/collections/dictionary.robot
src/robot/libraries/Collections.py

add optional default argument to Get From Dictionary

---

src/robot/conf/languages.py

Add thai language to language file

Add thai language

---

src/robot/conf/languages.py

Add Russian language support

---

src/robot/conf/languages.py

Adding Bosnian and Dutch Boolean

---

src/robot/conf/languages.py

provided by @mmalorni (https://github.com/mmalorni)

French True/False strings added

---

src/robot/conf/languages.py

provided by Miguel Angel Apolayo Mendoza

Updated Spanish Boolean values

---

src/robot/conf/languages.py

Swedish by @JockeJarre 
Bulgarian by @naschenez
Romanian by @zastress
Thank you all for your contribution!

Add Bulgarian, Romanian and Swedish localisation

---

src/robot/conf/languages.py

Provided by Luca Giorgi @lugi0

Added Italian

---

src/robot/conf/languages.py

Boolean translations for polish by Jerzy Głowacki

Add Polish Booleans

---

doc/userguide/src/CreatingTestData/Variables.rst

Fix Variables.rst

---

atest/robot/running/while/invalid_while.robot
atest/robot/running/while/while.robot
atest/robot/running/while/while_limit.robot
atest/testdata/running/while/invalid_while.robot
atest/testdata/running/while/while.robot
atest/testdata/running/while/while_limit.robot
doc/userguide/src/CreatingTestData/ControlStructures.rst
src/robot/parsing/model/statements.py
src/robot/running/bodyrunner.py

Add/modify tests and udpate documentation as well.
Fixes #4576

While: make condition optional

---

src/robot/model/testsuite.py

Completes type hinting in the test suite structure #4570
The files that got type hints added, where mainly files that I have interacted with as an end user. 
The PR is fully Compatible with Compatible with python 3.6 onwards.

Add some type hinting to the classes inside models. 

---

src/robot/conf/languages.py

Contributed by Hưng Trịnh (github username check pending)

Update languages.py with Vietnamese

---

src/robot/htmldata/htmlfilewriter.py

per https://developer.mozilla.org/en-US/docs/Web/API/HTMLStyleElement/type and https://html.spec.whatwg.org/multipage/obsolete.html#attr-style-type

remove deprecated type on style tag

---

src/robot/conf/settings.py
src/robot/htmldata/rebot/common.css
src/robot/htmldata/rebot/doc_formatting.css
src/robot/htmldata/rebot/log.css
src/robot/htmldata/rebot/log.html
src/robot/htmldata/rebot/report.css
src/robot/htmldata/rebot/report.html

This PR is just a local finalising of #4190

Dark mode log and report (finalising)

---

src/robot/htmldata/common/storage.js

Fix variable declaration in storage.js

---

atest/robot/variables/json_variable_file.robot
atest/robot/variables/yaml_variable_file.robot

atest may fail due to path parameter not wrapped with double qoutes

---

doc/userguide/src/CreatingTestData/TestDataSyntax.rst

Cleaned up verbiage in regards to the style guide.

Updated text about references to style guide

---

src/robot/result/executionresult.py
src/robot/result/xmlelementhandlers.py
utest/result/test_resultbuilder.py

Add generation_time to Result

---

src/robot/output/pyloggingconf.py

Restore root logging level

---

atest/robot/cli/dryrun/dryrun.robot
atest/robot/variables/variable_types.robot
atest/testdata/cli/dryrun/dryrun.robot
atest/testdata/variables/variable_types.robot
src/robot/parsing/model/statements.py
src/robot/running/arguments/argumentparser.py
src/robot/running/arguments/embedded.py
src/robot/running/arguments/typeinfo.py
src/robot/running/model.py
src/robot/running/userkeywordrunner.py
src/robot/variables/assigner.py
src/robot/variables/search.py
src/robot/variables/store.py
src/robot/variables/tablesetter.py
utest/parsing/test_model.py
utest/running/test_typeinfo.py
utest/running/test_userkeyword.py
utest/variables/test_search.py

Type converter to Robot data

---

atest/robot/variables/variable_types.robot
atest/testdata/test_libraries/Embedded.py
atest/testdata/variables/variable_types.robot
src/robot/running/librarykeywordrunner.py

Fix library embedded argument handling
