robotframework/robotframework

src/robot/utils/misc.py, utest/utils/test_misc.py
If the `.buffer` of an `io` module based stream was detached, the `stream.isatty()` method called in `utils.misc.isatty()` will raise a `ValueError`. As `utils.misc.isatty()` is usually only applied to `sys.stdout` and `sys.stderr` it most likely won't happen in __Python 2__. But who knows what other streams this function might be used with or what other projects might do with `sys.std...` before importing `robot`. And the buffer check is definitely needed for __Python 3__ compatibility. I encountered it recently on adding __Sphinx__ based docs to my __robotframework-tools__ project and running `setup.py build_sphinx` with __Python 3__, using a _conf.py_ which imports `robot`. And just imprting `robot` is enough, because the creation of `robot.output.logger.LOGGER` leads to the use of …
=> check for detached stream buffer in utils.misc.isatty()

utest/utils/test_normalizing.py
Some changes in `TestNormalizingDict` as discussed in https://github.com/userzimmermann/robotframework/issues/11 to simplify maintaining my [Python 3 compatibility fork](https://github.com/userzimmermann/robotframework) and making the official code step by step Python 3 compatible.
=> test_normalizing: some python3 compatibility fixes

doc/userguide/src/Appendices/DocumentationFormatting.rst, doc/userguide/src/CreatingTestData/AdvancedFeatures.rst, doc/userguide/src/CreatingTestData/CreatingTestCases.rst, doc/userguide/src/CreatingTestData/CreatingTestSuites.rst, doc/userguide/src/CreatingTestData/CreatingUserKeywords.rst, doc/userguide/src/CreatingTestData/ResourceAndVariableFiles.rst, doc/userguide/src/CreatingTestData/UsingTestLibraries.rst, doc/userguide/src/CreatingTestData/Variables.rst, doc/userguide/src/ExtendingRobotFramework/CreatingTestLibraries.rst, doc/userguide/src/ExtendingRobotFramework/RemoteLibrary.rst, doc/userguide/src/SupportingTools/Libdoc.rst
First phase of #1972
In this commit I just update the HMTL format to a Plain Text format.
I also updated the accompanying text when it was really needed.
There is still some work to do on
- reviewing the terminology (tables, rows, cells) but I will do this in another separate PL. The current version should be readable enough I hope.
- updating Pygments so that it handles the new dict variables
=> switch code samples in the User Guide from HTML format to Plain text format #1972

atest/testdata/parsing/data_formats/rest/sample.rst, src/robot/parsing/restreader.py
This is relative to issue #2093. The argument is that errors outside robot code blocks should be ignored when running robot. Still need to find a way to test this.
=> reST format: changed docutils report level to severe

doc/userguide/src/CreatingTestData/CreatingTestCases.rst
Tried running the example code locally and got an error "Maximum limit of started keywords exceeded."
It is because List files calls itself
=> Avoid a recursive call to List files

utest/reporting/test_jsmodelbuilders.py
The test intends to make sure that the TestSuite class produces the expected
behaviour. However, the test does not account for potentially compressed
strings that are produced inside the TestSuite class.
This patch compresses those strings to match what TestSuite would do.
Example to showcase the failure:
```bash
#!/bin/bash
readonly TEMP_DIR="$(mktemp -d)"
CLONE_DIR="$TEMP_DIR"
for i in {1..30}; do
CLONE_DIR+="/longdirname"
done
readonly CLONE_DIR
mkdir -p "$CLONE_DIR"
git clone https://github.com/robotframework/robotframework.git "$CLONE_DIR"/
pushd "$CLONE_DIR"
./utest/run.py
popd
rm -rf "$TEMP_DIR"
```
=> Fix a bug in the JS model builder tests

src/robot/libraries/Telnet.py
Telnet connections might be left open. Detected with Ubuntu 14.04 and is most likely valid for other distributions as well.
Cannot provide test case for this at the moment.
=> Telnet.py: Add missing shutdown()

doc/userguide/src/CreatingTestData/AdvancedFeatures.rst
The Documentation of the case, Float parameters should be "Loops over values 3.14, 4.34, and 5.54".
=> fix For-in-range loop Documentation in AdvancedFeatures.rst

src/robot/conf/settings.py, utest/conf/test_settings.py
fix for https://github.com/robotframework/robotframework/issues/2437
=> #2437 Options' default value of RobotSettings and RebotSettings should not be changed when running

src/robot/run.py
The --pythonpath, --argumentfile, --help, --version and --escape
arguments are not supported from the run method. Updated method
documentation to declare the exceptions.
=> Updates the run method documention by listing not supported arguments.

src/robot/model/modelobject.py, utest/model/test_keyword.py, utest/model/test_testcase.py, utest/running/test_run_model.py
Enable the `copy` and `deepcopy` feature of model objects.
This PR is the fix for that I mentioned in #2483 .
=> Model object should support copy and deepcopy

AUTHORS.txt, atest/robot/standard_libraries/builtin/verify.robot, atest/testdata/standard_libraries/builtin/verify.robot, src/robot/libraries/BuiltIn.py
This is the second set of keyword pairs for the case-insensitivity changes.  Covers the "Should Contain" and "Should Not Contain" keywords and their associated Acceptance Test cases.
=> Should (not) contain - keyword pair

AUTHORS.txt, atest/robot/cli/runner/rerunfailed.robot, atest/robot/cli/runner/rerunfailedsuites.robot, atest/robot/cli/runner/rerunfailedsuites_corners.robot, atest/testdata/cli/runfailed/runfailed1.robot, atest/testdata/cli/runfailed/runfailed2.robot, atest/testdata/cli/runfailed/suite/subsuite/suite_failed.robot, atest/testdata/cli/runfailed/suite/subsuite/suite_failed_with_excluded_tag.robot, atest/testdata/cli/runfailed/suite/subsuite/suite_succeed.robot, doc/userguide/src/Appendices/CommandLineOptions.rst, doc/userguide/src/ExecutingTestCases/ConfiguringExecution.rst, doc/userguide/src/ExecutingTestCases/PostProcessing.rst, src/robot/conf/gatherfailed.py, src/robot/conf/settings.py, src/robot/run.py
Based on [this issue](https://github.com/robotframework/robotframework/issues/2117) (I do need this functionnality too), I started implementing it.
:warning: this do not support the `--critical/noncritical`as I **need some advice**:
- shall I filter from first output (where for example `--noncritical`was set) : then I need to update the model to get the information when output is processed
- shall I only filter from second execution parameters
Can you also give me some comment about my work, what I need to change/correct if any.
Thanks!
=> Add --rerunfailedsuites option

BUILD.rst, tasks.py
As mentioned on `invoke` changelog, there was a backward incompatible change since version 0.13 [see changelog](https://github.com/pyinvoke/invoke/blob/master/sites/www/changelog.rst#id51)
This PR fixes invoke tasks on Python 2.7.
=> Adds "context" to invoke>=0.13 methods.

utest/utils/test_robottime.py
Looking at the source for Python 3.4, it appears that time.localtime()
is implemented such that it calls time(2) while time.time() calls
clock_gettime(2).
The phenomenon is such that performing the following reads:
1. time.localtime()
2. time.time()  - inside of _get_timetuple()
3. time.localtime()
the timestamps 1. and 3. return a time.struct_time with the tm_sec
field set to X. Occasionally, timestamp 2. returns a value of X+1.
This only appears to happen on a second boundary. The fraction
component of time.time() is in the sub-millisecond range.
Forcing all three timestamps to be sourced in the same way seems to
fix the problem.
On those occasional failures, I see the following printed:
AssertionError: (2016, 3, 13, 10, 40, 21) != (2016, 3, 13, 10, 40, 20)
=> De-flake test_get_current_timetuple_excluding_millis

doc/userguide/src/CreatingTestData/CreatingUserKeywords.rst
to clarify this "at the end the list variable gets all the leftover
arguments that do not match
other arguments."
You do not need the crate a list for multiple arguments.
=> Updated documentation on Varargs with user keywords, added testcase example

atest/robot/standard_libraries/dialogs/dialogs.robot, atest/testdata/standard_libraries/dialogs/dialogs.robot, src/robot/libraries/dialogs_py.py
Added one line to dialogs_py.py to resize the listbox. Added tests and run was ok for me, but I didn't check other versions. (Only on Ubuntu with python).
As this is my first contribution to a github project I'll be thankful for any help to improve my work.
=> issue 2517: Resize listbox for long values

atest/robot/cli/rebot/invalid_usage.robot, atest/robot/cli/runner/invalid_usage.robot, src/robot/result/keywordremover.py
The `--removekeywords` option supports tags, but this isn't reflected in the error message if used incorrectly:
> [ERROR ] Invalid value for option '--removekeywords'. Expected 'ALL', 'PASSED', 'NAME:<pattern>', 'FOR', or 'WUKS' but got 'TAGS:not_ready'.
This PR simply adds `'TAG:<pattern>'` to the error message.
=> Fix keyword remover usage error

CONTRIBUTING.rst
Resolves https://github.com/robotframework/robotframework/issues/2623.
https://github.com/robotframework/robotframework/pull/2676#issuecomment-328784771 says this section is outdated. Let's remove it, it's just confusing to contributors.
=> Docs: Remove outdated CI section

doc/userguide/src/CreatingTestData/CreatingTestSuites.rst
There is the list in the section "Test suite directories" has the list of ignored extensions. Although there is a link in the sentence with the actual list of supported extensions, I think it makes sense to keep the list up-to-date anywhere in the documentation.
=> Documentation fix: add forgotten extension .robot

src/robot/libraries/Screenshot.py
Use :class:`wx.Bitmap` instead of `wx.EmptyBitmap` due to a warning message below in execution:
wxPyDeprecationWarning: Call to deprecated item EmptyBitmap. Use :class:`wx.Bitmap` instead
bitmap = wx.EmptyBitmap(width, height, -1)
The version of wxPython 4.0.0b2 (the latest one).
=> Fix a warning message of keyword  'Take Screenshot' when using wxPython 4

doc/userguide/src/ExecutingTestCases/BasicUsage.rst
Added a note to the User Guide on calling pdb directly from within a test case using the builtin evaluate keyword.
=> Added note on calling pdb from a test case using evaluate

src/robot/libraries/BuiltIn.py
The example of "Should Contain" keyword (documentation) should use ignore_case instead of case_insensitive.
=> Correct example of "Should Contain"

atest/interpreter.py, atest/robot/standard_libraries/builtin/should_be_equal.robot, atest/robot/standard_libraries/builtin/should_be_equal_as_xxx.robot, atest/robot/standard_libraries/process/terminate_process.robot, atest/robot/standard_libraries/xml/xpath.robot, atest/run.py, atest/testdata/standard_libraries/builtin/variables_to_verify.py, atest/testdata/standard_libraries/collections/dictionary.robot, atest/testdata/variables/list_and_dict_variable_file.py, atest/testdata/variables/return_values.robot, src/robot/libraries/Remote.py, src/robot/reporting/jsexecutionresult.py, src/robot/reporting/stringcache.py, src/robot/running/namespace.py, src/robot/utils/__init__.py, src/robot/utils/robotpath.py, utest/utils/test_compat.py, utest/utils/test_dotdict.py
Resolves https://github.com/robotframework/robotframework/issues/2276.
Here's another branch with added Travis CI testing (thanks to @Brian-Williams for https://github.com/robotframework/robotframework/pull/2676!):
https://travis-ci.org/hugovk/robotframework/builds/287879614
Python 2.7, 3.3, 3.4, 3.5, 3.6, PyPy3 all pass. PyPy and Jython fail, but they do on latest master as well:
https://travis-ci.org/hugovk/robotframework/builds/287879614
=> Drop support for Python 2.6

atest/testdata/standard_libraries/collections/dictionary.robot, atest/testdata/standard_libraries/collections/list.robot
Changing list and dictionary tests for argument error to use named-only arguments.
=> Named-only arguments in dictionary error tests

atest/testdata/standard_libraries/operating_system/path_expansion.robot
Without this change, there were two test failures on Fedora Linux 28.
=> Add normalize path to USER env. var in path_expansion test case.

atest/testdata/keywords/type_conversion/PythonAnnotations.py, atest/testdata/keywords/type_conversion/python_annotations.robot, src/robot/running/arguments/typeconverter.py
This PR adds Enum support to the typeconverter and relevant tests.
Because the `enum` I added for the test starts with an upper case character I wasn't able to use the existing template for the expected failure.
=> Adds enum support to the typeconverter.

src/robot/libraries/Remote.py
Previously remote library connections only worked with HTTP, now works with both HTTP and HTTPS.
=> Allow Remote Library connection over HTTPS

src/robot/utils/importer.py
Currently, if robot imports a module by path, and that module prepends to sys.path, robot will pop the incorrect path from sys.path. I have changed this function to use remove() instead to fix this issue.
=> Changed _import_by_path to use path.remove() instead of path.pop()

src/robot/libraries/Collections.py
Libdoc parser has difficulty parsing the attached ``key`` / ``value``.
=> Fix collections documentation

doc/userguide/src/CreatingTestData/CreatingTasks.rst
Changed "It has been always been possible, bu Robot Framework 3.1..." to "It has been always been possible, but Robot Framework 3.1..."
=> User documentation: Fix typo in CreatingTasks.rst

src/robot/utils/etreewrapper.py, utest/result/test_resultbuilder.py, utest/utils/test_etreesource.py
This PR fix issue #3194.
I have updated and added some unit tests. But I have not added unit tests for `pathlib.Path` objects because `pathlib` requires Python 3.4 and these tests would not run with lower interpreter versions.
=> Support byte strings as ExecutionResult input (#3194)

src/robot/testdoc.py
The test filename passed as an argument should be my_test.robot, instead
of my_test.html.
Signed-off-by: Fathi Boudra <fathi.boudra@varian.com>
=> testdoc: fix typo in the execution examples

doc/api/code_examples/check_test_times.py, doc/api/generate.py, doc/libraries/extract_examples.py, doc/python/ExampleLibrary.py, doc/python/pt2html.py, doc/userguide/src/SupportingTools/LoggingLibrary.py
Legacy __print__ statements are syntax errors in Python 3 but __print()__ function works as expected in both Python 2 and Python 3.
=> Use print() function in both Python 2 and Python 3

src/robot/libraries/BuiltIn.py
* Fix typo
* Add an example for checking `None`
Signed-off-by: Stavros Ntentos <133706+stdedos@users.noreply.github.com>
=> Small changes to BuiltIn documentation

atest/robot/libdoc/cli.robot, atest/robot/libdoc/libdoc_resource.robot, src/robot/utils/robotio.py
This PR contains a fix for #2767. The acceptance test is only for Libdoc, as I  couldn't find any tests regarding `ROBOT_SYSLOG_FILE`. Ought to be fine though, since the same code is used for the two scenarios.
=> Ensure creation of missing directories for ROBOT_SYSLOG_FILE and Libdoc outputs

doc/releasenotes/rf-3.2a1.rst
Correct spelling of Language Server Protocol.
=> Fix typographical error in 3.2a1 release notes

atest/robot/standard_libraries/process/run_process_with_timeout.robot, atest/testdata/standard_libraries/process/run_process_with_timeout.robot, src/robot/libraries/Process.py
Make `timeout` named argument accept the same values as keyword `[Timeout]` does.
`None` (case-insensitively), falsy, zero or negative values are treated
the same way as `[Timeout]` (i.e. ignored aka infinity)
This is in addition to `${None}` being already ignored.
See also robotframework/robotframework#3365
Resolves robotframework/robotframework#3366
Signed-off-by: Stavros Ntentos <133706+stdedos@users.noreply.github.com>
=> Normalize `Run Process | ... | timeout=0`

doc/userguide/src/GettingStarted/Introduction.rst
I was shocked by a "new RRA support" displayed in Google when searching for RobotFramework doc.
=> Fixed RPA documentation typo

src/robot/libraries/Collections.py
If the `end` of slice is not explicit, the bug will follow.
E.g. ```Get Slice From List  ${L5}  end=-2``` is correct:
=> Fixed typo in documentation for `Get Slice From List`.

doc/userguide/src/SupportingTools/LoggingLibrary.html, src/robot/htmldata/libdoc/libdoc.html
Adds functionality to automatically select tags in libdoc html documantetion if query string "tag=$tag_to_select" is passed to it.
Another commit where around this same topic as the element title said "tests" but at least in libdoc context, they where referring to document tags.
#3440
=> Issue 3440

doc/userguide/src/Appendices/DocumentationFormatting.rst, src/robot/utils/htmlformatters.py, utest/utils/test_markuputils.py
This PR adds .svg extensions to the list of image types that are automatically converted into &lt;img&gt; tags in documentation fields.
I modified the only unittest I found for this functionality. There didn't seem to be any existing acceptance tests.
Related to issue: #3464
=> Add support for svg image link

atest/robot/standard_libraries/collections/list.robot, atest/testdata/standard_libraries/collections/list.robot, src/robot/libraries/Collections.py
1.  As list is mutable and if we use sort, it will alter original list.  Original list should not be altered so used sorted function instead of sort method. 
2. Instead of modify more lines in the _yield_list_diffs method to handle `name` option given by user, just passed sorted list to get the diff as we should support name argument/parameter as well.
=> List ignore

.github/workflows/unit_tests.yml
CodeCov action has been upgraded today to support:
- proper handling for pull requests
- tokenless upload functionality
See https://github.com/codecov/codecov-action/releases/tag/v1.0.6.
=> Upgrade codecov to 1.0.6

src/robot/running/arguments/argumentparser.py
This corrects a bug that causes an unhandled exception for test libraries with Optional[] parameters in Python 3.5. Included is a minimal test case for this issue: Running this in python 3.6 or python 3.5 with my change will work fine, but Python3.5 with the robot framework as-is will produce:  
```
njewers@njewers-lt:~/workspace/robottest$ python3.5 -mrobot union.robot
[ ERROR ] Unexpected error: AttributeError: type object 'Union' has no attribute '__args__'
Traceback (most recent call last):
File "/home/njewers/.local/lib/python3.5/site-packages/robot/utils/application.py", line 83, in _execute
rc = self.main(arguments, **options)
File "/home/njewers/.local/lib/python3.5/site-packages/robot/run.py", line 439, in main
result = suite.run(settings)
File …
```
=> Fixed ArgumentParser union type handling under Python 3.5

atest/interpreter.py, atest/run.py
When running Jython >= 2.7.2 on Java >= 9, unexpected printouts are present on stdout, set JAVA_OPTS to `--add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED` to avoid that.
References #3501.
=> Acceptance tests on Jython 2.7.2 with Java >= 9

.github/workflows/acceptance_tests_cpython.yml, .github/workflows/acceptance_tests_jython.yml
It would be better to receive fixes to setup-python action automatically within 1.x version. @Hi-Fi, would you take a look?
=> Enable upgrade of setup-python action within 1.x version

.github/workflows/acceptance_tests_jython.yml, .github/workflows/unit_tests.yml
- Drop running tests on Jython 2.7.1 / Java 8
- Start runnig tests on Jython 2.7.2 / Java 8
=> Migrate workflows to Jython 2.7.2 on Java 8

atest/testdata/keywords/type_conversion/Annotations.py, atest/testdata/keywords/type_conversion/KeywordDecorator.py, atest/testdata/keywords/type_conversion/annotations.robot, atest/testdata/keywords/type_conversion/keyword_decorator.robot, doc/userguide/src/ExtendingRobotFramework/CreatingTestLibraries.rst, src/robot/running/arguments/typeconverters.py
I have implemented the enhancement proposed in issue #3611. The changes are backwards compatible as the member is first matched without normalization.
=> Enum conversion with normalized names. Implements #3611

src/robot/htmldata/libdoc/libdoc.html
We should put this behind a command line flag or such to let users choose if splitting is preferred.
=> Split keyword argument lines

src/robot/output/console/highlighting.py
This fixes the stack trace I have below when running robotframework with pytest in a windows console (although I'm not sure why it happens in the first place... pytest probably does some mocking that robotframework doesn't like).
```
File "c:\bin\miniconda\envs\py_38_tests\lib\site-packages\robot\run.py", line 492, in run_cli
return RobotFramework().execute_cli(arguments, exit=exit)
File "c:\bin\miniconda\envs\py_38_tests\lib\site-packages\robot\utils\application.py", line 46, in execute_cli
rc = self._execute(arguments, options)
File "c:\bin\miniconda\envs\py_38_tests\lib\site-packages\robot\utils\application.py", line 91, in _execute
return self._report_error('Unexpected error: %s' % error,
File "c:\bin\miniconda\envs\py_38_tests\lib\site-packages\robot\utils\application.py", line 106, …
```
=> Also suppress errno.EBADF for broken pipe error

src/robot/htmldata/libdoc/libdoc.css, src/robot/htmldata/libdoc/libdoc.html
Hi,
when reading the library documentation in a web browser, I would like to have a list of the "shortcuts" (keywords) one per line, because for me it seems easier to read.
With the attached pull request, the HTML page created by libdoc looks like this:
A click on "One per line" switches the list to one keyword per line:
The new optional "One per line" shortcuts list style takes more vertical place. However, it may be easier to spot a specific keyword than in the compact list. It is possible to switch back to the original style in the browser.
Tested for the libraries from Robot Framework source and for SeleniumLibrary in Google Chrome 84, Mozilla Firefox 79 and Internet Explorer 11.
Best Regards,
Rudolf
=> Libdoc html in-browser switch to list one shortcut per line

.github/workflows/acceptance_tests_jython.yml
Recently, Github Actions started defining "JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8" variable on Linux hosts, but this variable prevents acceptance tests from proper execution.
The error is:
```
Traceback (most recent call last):
File "atest/run.py", line 126, in <module>
rc = atests(*sys.argv[1:])
File "atest/run.py", line 58, in atests
interpreter = InterpreterFactory(interpreter)
File "/home/runner/work/robotframework/robotframework/atest/interpreter.py", line 21, in InterpreterFactory
return Interpreter(path, name, version)
File "/home/runner/work/robotframework/robotframework/atest/interpreter.py", line 30, in __init__
name, version = self._get_name_and_version()
File "/home/runner/work/robotframework/robotframework/atest/interpreter.py", line 49, in _get_name_and_version
version = …
```
=> Fix tests on Jython 2.7.2 (Java 8) on Linux/Ubuntu

atest/robot/standard_libraries/builtin/get_variable_value.robot, atest/robot/standard_libraries/string/split_string.robot, atest/robot/standard_libraries/string/string.robot, atest/robot/standard_libraries/xml/element_attribute.robot, atest/robot/standard_libraries/xml/set_element_information.robot, atest/testdata/standard_libraries/builtin/get_variable_value.robot, atest/testdata/standard_libraries/operating_system/env_vars.robot, atest/testdata/standard_libraries/string/convert_to.robot, atest/testdata/standard_libraries/string/split_string.robot, atest/testdata/standard_libraries/string/string.robot, atest/testdata/standard_libraries/xml/element_attribute.robot, atest/testdata/standard_libraries/xml/set_element_information.robot, src/robot/libraries/BuiltIn.py, src/robot/libraries/OperatingSystem.py, src/robot/libraries/String.py, src/robot/libraries/XML.py
This is a PR for #3649. Opted for using the `@keyword(types=None)` decorator. Added one acceptance test for all the applicable cases.
=> Disable automatic type argument conversion (`none` => `None`) on some keywords.

.github/workflows/acceptance_tests_cpython.yml, atest/requirements.txt
Also, make sure that Pillow and lxml libraries are at the end of
atest/requirements.txt, so install errors don't impact other 3rd
party libraries.
=> Exclude tests that require lxml or Pillow from CI runs on Win + Python 3.9

doc/userguide/src/CreatingTestData/Variables.rst
${ESCAPED} gets the value "quotes and spaces" , removed as its not quoted in example.
=> Removed unused escaped example.

INSTALL.rst, README.rst, setup.py
=> Remove EOL Python 3.4 from officially supported versions in setup.py and README

atest/robot/libdoc/console_viewer.robot, atest/robot/libdoc/default_escaping.robot, atest/robot/libdoc/html_output.robot, atest/robot/libdoc/html_output_from_json.robot, atest/robot/libdoc/html_output_from_libspec.robot, atest/robot/libdoc/json_output.robot, atest/robot/libdoc/module_library.robot, atest/testdata/libdoc/default_escaping.py, atest/testdata/libdoc/default_escaping.resource, atest/testdata/libdoc/module.py, src/robot/libdocpkg/robotbuilder.py
Escape robot special chars in argument default value representations. To support better default values in libdoc.
=> Topic/robot repr (fixes #3697)

doc/schema/robot.02.xsd
Differentiate test and suite statuses from other statuses, as "NOT RUN" is only available for keywords, FORs and IFs.
Related to #3726.
=> differentiate test and suite statuses from other statuses

src/robot/utils/markupwriters.py, utest/result/test_resultbuilder.py
This fixes a simple omission for supporting Path objects
=> Support using pathlib.Path with markupwriters

atest/robot/keywords/type_conversion/unions.robot, atest/testdata/keywords/type_conversion/keyword_decorator.robot, atest/testdata/keywords/type_conversion/unions.py, atest/testdata/keywords/type_conversion/unions.robot, src/robot/running/arguments/typeconverters.py
#3867
#3738
If a value is already a valid type from a type union then there is no need to convert it.
=> Don't convert value if it is already a valid type.

doc/userguide/src/ExtendingRobotFramework/CreatingTestLibraries.rst
While reading the user guide I found a typo. Maybe you want to fix this, although I can understand that maybe more important issues will be preferred. Thank you for your work! 😄
=> Fixed Typo in User Guide

src/robot/htmldata/libdoc/libdoc.css
Fixes #4012 
Note: [overscroll-behavior](https://caniuse.com/css-overscroll-behavior) CSS property isn't yet supported on Safari. However, the keyword documentation pages seemed to work as they do now.
=> Fix keyword documentation shortcuts menu overflow and overscroll

.github/workflows/unit_tests_pr.yml
These data don't make much sense without collecting coverage
data also for acceptance tests. Decided to disable it.
=> Disable collecting unit tests code coverage data for PRs

atest/testdata/running/continue_on_failure_tag.robot, doc/userguide/src/ExecutingTestCases/TestExecution.rst, src/robot/running/context.py
minor modifications to #3925, renaming the recursive tag as `robot:recursive-continue-on-failure` and modified tests to also use upper-case or whitespace in those reserved tags.
I did not mix case for the tagstatistic tests as it seems, I had to do below to make it pass 
``` 
def _suppress_reserved(self, tag):
-        return tag.startswith('robot:') and not self._included.match(tag)
+        return tag.lower().startswith('robot:') and not self._included.match(tag)
```
full diff required to make the test pass when I use ROBOT: prefix.. this doesn't look correct..don't have time this week to look at this..
```
diff --git a/atest/robot/tags/tag_stat_include_and_exclude.robot b/atest/robot/tags/tag_stat_include_and_exclude.robot
index a13b5ba9e..76e697992 100644
--- …
```
=> rename continue-on-failure-recursive tag to robot:recursive-continue-on-failure

doc/userguide/src/ExtendingRobotFramework/ListenerInterface.rst
Hey, hope it's alright to open a PR for this type of thing. I was browsing through the listener documentation and copied an example. I then noticed that this example had a slight indentation issue (lines 579 and line 582). This PR fixes that slight indentation issue
=> fix indentation issue in ListenerInterface documentation

atest/testdata/parsing/data_formats/rest/sample.rst, src/robot/utils/restreader.py
Closes #4086. This patch decorates `docutils` functionality so as to ignore every directive and role that is not directly relevant to RobotFramework. Alternative to error suppression (through `report_level` configuration, see https://github.com/robotframework/robotframework/issues/2093).
=> Narrow down the scope of ReST parsing.

atest/robot/standard_libraries/builtin/log.robot, atest/testdata/standard_libraries/builtin/log.robot, atest/testdata/standard_libraries/builtin/should_be_equal.robot, src/robot/libraries/BuiltIn.py
Resolves #4095
- Adds the len (suggested) and type formatter options to _get_formatters used by Log.
- Acceptance tests added for each.
- Doc and error message modifications.
Made an attempt at the additional suggestion in #4095 to support any builtin but couldn't get it down. After looking at the [list of builtins](https://docs.python.org/3/library/functions.html) as well I am not confident that I am not opening some can of worms in the process there. :sweat_smile:
=> Add len and type log formatter options to log keyword

atest/robot/standard_libraries/process/process_library.robot, atest/testdata/standard_libraries/process/process_library.robot, atest/testdata/standard_libraries/process/terminate_process.robot, src/robot/libraries/Process.py, src/robot/utils/connectioncache.py
Modifies create_process method as it returns a process object.
Iterable for process objects  goes through connection indexes
so we can directly call get_connection for generated index from
register method.
Fixes #4104
=> Process: Return created process object

atest/robot/output/xunit.robot, src/robot/reporting/xunitwriter.py
Resolves issue #4074 by adding the timestamp attribute to testsuite element in xunit output. The timestamp is generated from the testsuite ```starttime``` which seems to be procedure in other tools as well. Furthermore, strong assumption is done that RF starttime format is always ```YYYYMMDD hh:mm:ss.mil```. Starttime with empty string ```''``` or ```None``` yields xunit timestamp attribute to empty value as well: ```timestamp=""```.
Valid RF starttime yields e.g. ```2021-11-10T21:34:30.006000```
=> Resolves  #4074 Add timestamp attribute testsuite element in xunit output

atest/robot/output/xunit.robot, atest/robot/rebot/xunit.robot, src/robot/reporting/xunitwriter.py
Introduces xunit output with separate <testsuite> element for each of suite. Allows nested suites targeting to design topics mentioned in #2982.
=>  Resolves #2982 xUnit outputs: Add separate <testsuite> entries for each suite

atest/robot/standard_libraries/builtin/log_variables.robot, atest/robot/variables/automatic_variables.robot, atest/testdata/variables/automatic_variables/auto1.robot, atest/testdata/variables/automatic_variables/auto2.robot, doc/userguide/src/CreatingTestData/Variables.rst, src/robot/variables/scopes.py
This PR adds a new disctionary "SETTINGS" to the automatic variables to expose exclude and include tags command line options (for now).
Based on previous discussions in #4052
=> Add SETTINGS dictionary to automatic variables to expose command line options (Issue #4229)

src/robot/htmldata/libdoc/libdoc.css, src/robot/htmldata/libdoc/libdoc.html
- hide type documentation list from the bottom of doc
- clicking type opens a modal with type documentation
- close modal by eithet clicking background, clicking close-button or pressing esc
- support for desktop and mobile layouts
=> Modals for type definitions to docs

doc/userguide/ug2html.py, requirements-build.txt
Fixes #4264.
The RobotFramework lexer has long been included in Pygments now, and
the robotframeworklexer copy on PyPI wast last updated earlier 2019.
* doc/userguide/ug2html.py: Do not import robotframeworklexer, check
its version nor use it.  Bump Pygments requirement to 2.8, as that's
old enough and is what was used to test.
* requirements-build.txt: Drop robotframeworklexer requirement.
Update pygments required version.
=> doc: ug2html.py: Do not depend on robotframeworklexer.

README.rst
Closes #4260 
Updated README as per the comments by @pekkaklarck  on Issue #4260 for RF5
> Remove references to Python 2, Jython, etc. from descriptions, examples, etc.
Mention that RF 5.0 requires Python 3.6 or newer.
Mention that RF 4.1 still supports Python 2, Jython and IronPython. There should be a link either to the PyPI page or GitHub tag of the latest RF 4.1 release.
=> Updated README as per RF5 Issue 4260

BUILD.rst, atest/robot/libdoc/html_output.robot, atest/robot/libdoc/json_output.robot, atest/robot/libdoc/libdoc_resource.robot, atest/robot/libdoc/spec_library.robot, atest/robot/standard_libraries/operating_system/modified_time.robot, atest/testdata/standard_libraries/builtin/get_time.robot, atest/testdata/standard_libraries/operating_system/modified_time.robot, doc/userguide/ug2html.py, src/robot/libdocpkg/model.py, src/robot/libdocpkg/output.py, src/robot/libdocpkg/xmlwriter.py
Fixes #4262.
* doc/userguide/ug2html.py (create_userguide): Do not embed
timestamps.
* src/robot/utils/robottime.py (get_timestamp_for_doc): New procedure.
* src/robot/utils/__init__.py: Export it.
* src/robot/libdocpkg/model.py (LibraryDoc.to_dictionary): Use it.
* src/robot/libdocpkg/xmlwriter.py (LibdocXmlWriter._write_start):
Likewise.
* BUILD.rst: Document it.
=> doc: Honor SOURCE_DATE_EPOCH for documentation timestamps.

doc/userguide/src/ExtendingRobotFramework/CreatingTestLibraries.rst
The current version of the inheritance example does not work, because `SeleniumLibrary` needs `keyword` decoration for implemented methods to be recognized as Robot Framework keywords.
Either update according to my changes or switch to some other example that does not require decoration.
https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#using-inheritance
=> User guide: Update inheritance example

atest/robot/libdoc/html_output.robot, atest/robot/libdoc/json_output.robot, atest/robot/libdoc/resource_file.robot, atest/robot/running/private.robot, atest/testdata/libdoc/resource.robot, atest/testdata/running/private.resource, atest/testdata/running/private.robot, atest/testdata/running/private2.resource, atest/testdata/running/private3.resource, doc/userguide/src/CreatingTestData/CreatingUserKeywords.rst, src/robot/libdocpkg/htmlwriter.py, src/robot/libdocpkg/model.py, src/robot/running/context.py, src/robot/running/namespace.py, src/robot/running/userkeywordrunner.py
Resolves #430.
- User keywords can now be marked as private by tagging them `robot:private`.
- Using them in resources within the same file is fine and intended
- Using them in a test case in the same file or in a user keyword in another file will cause a warning
- Keywords tagged as `robot:private` are removed from libdoc's html output
- They are, however, still included in libdoc's spec files, for other tools to pick up on them
- If there is both a public and a private User Keyword with the same name in the current scope, Robot Framework will execute the public one
=> Keyword visibility modifiers for resource files (#430)

src/robot/conf/languages.py
I've actually provided direct translations but also alternatives. For example 'Test cases' directly translated is 'Przypadki testowe' but it sounds a bit stiff so most people would just say 'Testy' or 'Scenariusze' (with BDD). 
But it could be good to have way to add alternatives to some of the markers, such as 'Keyword Tags'. In this case 'Keyword -> 'Słowo kluczowe' but good alternative is 'Funkcja' so 'Keyword Tags' could be 'Znaczniki słowa kluczowego' or 'Znaczniki funkcji'. WDYT @pekkaklarck ? (I think only headers allow to define sets, not string values).
=> Add polish language

src/robot/conf/languages.py
In german the plural form of the english word "Variables" is "Variablen". Maybe we can change this ;-)
=> Change german Variables to plural form

src/robot/htmldata/libdoc/libdoc.html
Datatype `Proxy` conflicts with function `Proxy` therefore type doc can not be shown in HTML.
=> Fixes issue #4464 when naming conflicts happen in libdoc datatypes

src/robot/libraries/BuiltIn.py
I know from experience that when you provide a value for the `Sleep` keyword, that this value defaults to seconds.
However, when I tried to verify that in the documentation and in the keyword's definition, I couldn't.
That is the reason I am raising this PR. Since it confused me, it will confuse others as well.
Feel free to reject my PR and write it with your own wording. It doesn't matter much to me, as long as we explicitly mention it in Sleep's docstring.
=> Explain Sleep's default value is seconds

atest/robot/cli/console/colors_and_width.robot, atest/robot/cli/runner/argumentfile.robot, atest/robot/cli/runner/rerunfailedsuites_corners.robot, atest/robot/cli/runner/run_empty_suite.robot, doc/userguide/src/ExecutingTestCases/BasicUsage.rst, src/robot/utils/argumentparser.py, utest/utils/test_argumentparser.py
Hello everyone,
This PR fixes #4547.
It adds support for the usual CLI options as well as the special "--argumentfile" option (#2535).
I added a few unit tests and edited some existing acceptance tests.
I also updated the user guide to briefly describe the new behavior.
Thank you in advance for taking the time to review this PR, and please let me know if I need to fix anything.
=> Support long command line options with hyphens like --pre-run-modifier

utest/running/test_imports.py
These tests are failing for me on my machine after downloading robotframework and running:
`python utest/run.py -q running`
The failure message was just:
`AssertionError: FAIL != PASS`
With this PR it is:
```
(py311_tests) λ python utest/run.py -q running
======================================================================
FAIL: test_create (test_imports.TestImports.test_create)
----------------------------------------------------------------------
Traceback (most recent call last):
File "X:\robocorpws\robotframework\utest\running\test_imports.py", line 33, in run_and_check_pass
assert_suite(result, 'Suite', 'PASS')
File "X:\robocorpws\robotframework\utest\running\test_imports.py", line 16, in assert_suite
assert_equal(suite.status, status)
File …
```
=> Improve failure message on test failure.

src/robot/model/testcase.py, src/robot/model/testsuite.py
1. Added type hints to `model.testcase`
2. minor change to `model.testsuite` to keep consistent with the convention of no spaces inside stringified type hints
=> Add type hints for model.testcase

src/robot/model/__init__.py, src/robot/model/itemlist.py, src/robot/model/testcase.py, src/robot/model/testsuite.py, src/robot/result/model.py, src/robot/running/model.py, src/robot/utils/__init__.py, src/robot/utils/typehints.py
The decorator allows function definitions to shadow other function definitions. 
It has a similar behaviour as `@wraps`, but works purely with type hints.
ItemList working
Body working
Part of #4570
=> Add the @set_type_hints decorator

src/robot/model/body.py, src/robot/model/testcase.py, src/robot/result/model.py, src/robot/running/model.py
- `Body` sub classes pass in correct types
-  Those types are used with @copy_signature to type the `create_xxx` methods
-  Added correctly typed `body` entries for `running.TestCase` and `result.TestCase`
**Examples of the PR working**
Unfortunately, One side effect of this PR is, that Pyright believes that `Body.register` methods are cyclical dependencies.
=> Make model.BaseBody accept Generic parameters

src/robot/model/fixture.py, src/robot/model/keyword.py, src/robot/model/testcase.py, src/robot/model/testsuite.py, src/robot/result/model.py, src/robot/running/model.py, utest/model/test_fixture.py
`create_fixture` takes a fixture class parameter, making the function generic. 
Unit tests have also been updated to reflect this
=> Make fixture generic to enable type hinting

doc/userguide/src/CreatingTestData/CreatingUserKeywords.rst
Update documentation setting to reflect that this is for keywords, not tests.
=> Clarify code example

doc/userguide/src/CreatingTestData/CreatingTestSuites.rst
Correct a typo 'a test teardown' where 'a suite teardown' is intended.
=> Correct a typo in CreatingTestSuites.rst

atest/robot/running/stopping_with_signal.robot, atest/testdata/running/stopping_with_signal/AsyncStop.py, atest/testdata/running/stopping_with_signal/async_stop.robot, doc/userguide/src/ExtendingRobotFramework/CreatingTestLibraries.rst, src/robot/running/context.py
This will only cancel the task that got the error. Other coroutines will still run normally.
We can try to clean up coroutines when closing the loop, but i think showing the logs of open tasks help developers manage the coroutines better, so i didn't include any clean up for that. Open to suggestions on this.
Adressing issue #4808
=> if execution cannot continue, cancel task and its children

src/robot/htmldata/rebot/common.css, src/robot/htmldata/rebot/log.css, src/robot/htmldata/rebot/log.html, src/robot/htmldata/rebot/report.html, src/robot/htmldata/rebot/view.js
@pekkaklarck This implements a theme toggle butten at top left of log and report.
By default the system setting is used.
If toggle is clicked, it is stored in localStorage.
Additionally it is possible to add `?theme=dark` or `?theme=light` to the url and you directly get the requested theme.
maybe this can still be tried out in RC1 ?
=> implemented dark_light theme toggle button

src/robot/model/body.py, src/robot/model/control.py, src/robot/model/testcase.py, src/robot/model/testsuite.py, src/robot/running/model.py
I was checking my contributions to the previous version of robotFramework were still functional in the RF 7.0 beta. I noticed some small issues.  
- Fixed a couple of instances of overzealous find-and-replace
- Fixed some missing imports
- Added some missing type arguments to Generic classes
=> Miscellaneous type hint fixes

src/robot/libraries/String.py
Without zero for the start index the end index would be parsed as the start index argument.
=> String: Fix get substring example missing start index

src/robot/htmldata/rebot/common.css, src/robot/htmldata/rebot/log.html
This fixes the broken highlighting of the taget test element.
(The one jumped to with #s1-s1-t1 etc.)
It now uses standard css for this.
See [Slack Discussion](https://robotframework.slack.com/archives/C0K0240NL/p1704455170871919?thread_ts=1704392651.216979&cid=C0K0240NL) as well.
=> improved and fixed broken link target highlighting

utest/utils/test_error.py
Python 3.13+ introduces some additional characters to exception descriptions containing the `~` character. Filter them out as well like the `^` previously handled.
Closes #5035
=> utest: Improve filtering of output sugar for Python 3.13+

doc/api/conf.py
Since end of 2023, the default theme at ReadTheDocs has been changed to Alabaster.
This change will make sure the classic ReadTheDocs theme is used again.
If you want to check the document creation locally, you can do that my running
`TZ=UTC make html`
(`TZ=UTC` was needed on my system due to a timezone error)
When building locally, make sure to install the packages `sphinx_rtd_theme`.
via `pip install sphinx_rtd_theme`.
When building via ReadTheDocs, this is not needed as their standard image for building includes that package
=> Use 'sphinx_rtd_theme' as theme

src/robot/running/model.py
changes 'included_tags' to 'include_tags' in TestSuite.configure() docstring
=> fix argument name in docstring

atest/robot/standard_libraries/dialogs/dialogs.robot, atest/testdata/standard_libraries/dialogs/dialogs.robot, src/robot/libraries/dialogs_py.py
Closes #4993
Reverting the change introduced in the fix for #1466 and fixing it in a different way without the side effect of #4993.
=> Fixed Tcl_AsyncDelete crash after closing dialog (#4993)

doc/userguide/src/CreatingTestData/CreatingTestCases.rst
The link for description of ATDD was broken, changed to a link to the Wikipedia ATDD page
=> Fixed broken link for ATDD

atest/testdata/standard_libraries/datetime/convert_time_input_format.robot, doc/userguide/src/Appendices/TimeFormat.rst, src/robot/libraries/DateTime.py, src/robot/utils/robottime.py, utest/utils/test_robottime.py
This PR fixes #5135 and stands as a potential implementation for a "week" as a valid unit of time in a time string.
Documentation was updated to indicate that a "week" is now a valid unit of time. Furthermore, unit tests were also added to ensure backwards compatibility. I should call out that one of the unit tests ensuring invalid formats raise an exception needed to be modified from `w` to `y` in order to pass. I *think* the intent of this unit test was to ensure that units of time must be sorted (e.g. days, then hours, then minutes, etc.) and not reversed/arbitrary (minutes, then weeks, then days, etc.). However, if I misinterpreted that and need to modify the unit tests somehow, let me know!
=> feat: Add support for "week" as a valid unit of time in time strings

atest/robot/keywords/optional_given_when_then.robot, atest/testdata/keywords/optional_given_when_then.robot, doc/userguide/src/CreatingTestData/CreatingTestCases.rst, src/robot/running/namespace.py
This is a fix for issue #4577.
From Specification by Example's best practices action steps are best written in third person form where the actor is named that performs the action. Oftentimes you want the actor to be a variable, because the actions of the different actors have different consequences.
For example:
> Given Alvin Admin is logged in on the portal
> and Betty Buyer is logged in on the portal
> then Alvin Admin sees Betty Buyer in the online users list
> but Betty Buyer cannot see Alvin Admin in the online users list
Before this fix, implementing a keyword like `${user} is logged in on the portal` would, in the given step, yield the faulty effect that `${user}` gets the value "_Given Alvin Admin_".
=> Allow keywords starting with a variable in bdd style

atest/robot/standard_libraries/builtin/should_contain.robot, atest/testdata/standard_libraries/builtin/should_contain.robot, atest/testdata/standard_libraries/builtin/variables_to_verify.py, src/robot/libraries/BuiltIn.py
Implemented as described in the issue.
Fixes #5054.
=> Fixes #5054: Enhance Should Contains for bytes

src/robot/output/console/highlighting.py
In the `AnsiHighlighter` class, the method for creating file URLs has been improved. Instead of manually constructing the URL via string formatting, `Path.as_uri()` is now used.
**Why `Path.as_uri()`?**
- **Robustness**: Ensures correct and OS-independent URL formatting.
- **UNC Paths**: Properly handles UNC paths, avoiding common pitfalls.
- **Character Escaping**: Automatically escapes special characters to ensure a valid URL.
- **Local Files**: Omits unnecessary hostname for local files
- **Error Prevention**: Reduces potential errors and inconsistencies in URL construction.
=> use `as_uri` to build the link in AnsiHighlighter

.github/workflows/acceptance_tests_cpython.yml, .github/workflows/acceptance_tests_cpython_pr.yml, atest/robot/cli/console/colors_and_width.robot
This PR introduces rflogs integration to GitHub Actions workflows, improving ability to track and analyze test failures across different environments.
- Added rflogs upload step to acceptance test workflows (both push and PR)
- Made the result dir discovery platform independent by using python
- Removed deprecated result upload steps
- Configured rflogs to upload results only on test failures
- Included relevant tags for better context:
- os
- python-version
- branch
- RFLOGS_API_KEY is set in repository secrets ( I did it )
- RFLOGS_API_KEY points to a project that I own in rflogs.io as the service is still WIP (this could be changed later).
From https://github.com/robotframework/robotframework/actions/runs/11196642558
```
HTML Files:
Report: …
```
=> Add rflogs integration for improved test failure tracking

atest/robot/standard_libraries/builtin/set_documentation.robot, atest/robot/standard_libraries/builtin/set_suite_metadata.robot, atest/robot/standard_libraries/builtin/set_test_message.robot, atest/testdata/standard_libraries/builtin/documentation/set_documentation.robot, atest/testdata/standard_libraries/builtin/set_suite_metadata.robot, atest/testdata/standard_libraries/builtin/set_test_message.robot, src/robot/libraries/BuiltIn.py
Added an argument `separator` in `Set Test Message`, `Set Test Documentation`, `Set Suite Documentation` and `Set Suite Metadata` keywords. This allows passing in custom separators when appending the data.
Added steps in existing acceptance tests. Added new acceptance tests where required.
Closes #5215
=> Added separator argument in `Set Test Message`, `Set Test Documentation`, `Set Suite Documentation` and `Set Suite Metadata` keywords.

atest/robot/standard_libraries/collections/list.robot, atest/testdata/standard_libraries/collections/list.robot, src/robot/libraries/Collections.py
Fixes #5321 
Moved the step to normalize the case before sorting the list.
=> Fix `Lists should be equal` with `ignore_case` and `ignore_order`

src/robot/conf/languages.py
This how it looks like on the vscode and on the logs
I believe that it can be good first step for supporting RTL languages . It's current state is already understandable and common sense display ( since that mixing RTL and LTR is common behavior already for RTL speakers )
further support could be adding RTL ability in the HTML logs and reports
=> add arabic

doc/userguide/src/ExecutingTestCases/TestExecution.rst
Seems like this is not mentioned anywhere else. I scratched my head on it for a while.
It appears that the term "ERROR" is used for different purpose in TRY/EXCEPT (i.e. exception or failure) or logging (i.e. level).
Maybe it would be valuable to also mention it in the TRY/EXCEPT section :
```rst
.. note:: TRY/EXCEPT do not catch "ERROR" level logs, therefore they will not prevent exiting when :option:`--exitonerror` is used.
```
=> Mention logging with ERROR level when using --exitonerror

CONTRIBUTING.rst
As discussed on Slack: added a section about type hints / annotations to the contributions guide to serve as guideline for the planned annotations work on the standard libraries.
=> Python 2 reference removed, added section for type hints / annotations
